### ISSUE TITLE
Race-condition between `dockutil` screen update and next command

### ISSUE THREAD

**Issue by JBarrskog** [geerlingguy/ansible-collection-mac#43]
The screen of my 16" M1 MacBook Pro flashes and reloads(?) the dock every time a change is made to the dock. This results in a race-condition, resulting in me having to run the `dock`-module several times until all changes to the dock are made. 

**Suggestion:**
Add a 1 second delay after each alteration to the dock, to give time for the reloading.

EDIT:
The role could perhaps run recursively until no changes are made.

**Comment by geerlingguy** [comment]
Merged the dock command pause-between-changes PR above—it's not the prettiest thing in the world, but at least it should work better (especially if the Mac is burdened with some other stuff).

It's annoying if you have like 20+ Dock items, because that's a minimum of 2+ minutes... but at least it'll run through all the way. Another idea is to add `retry` functionality. That could allow it to run as fast as possible and just loop on the stuck command until all else fails.

I'll add a separate issue to explore that: https://github.com/geerlingguy/ansible-collection-mac/issues/53
